name: jianshutoblog

on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: spider
      run: |
        pip3 install requests
        python3 jiansshuspideer.py
    - name: commit
      run: |
        git config --global user.email jackyu0915@gmail.com
        git config --global user.name JackietYu
        git add .
        git commit -m "Everyday update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          source-repo: "git@github.com:JackietYu/jianshutoblog.git"
          destination-repo: "git@gitee.com:JackietYu/jianshutoblog.git"
