name: jianshutoblog

on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Update paper list
      run: |
        python jiansshuspideer.py

    - name: commit
      run: |
        git config --global user.email jackyu0915@gmail.com
        git config --global user.name JackietYu
        git add .
        git commit -m "Everyday update" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
